# Je suis 

**Onesime Mbulayi**, Phd Candidate

**Domain de Recherche : Machine Learning & Bioinformatique**

# 1.0 Introduction

NumPy est la base de le moteur d'apprentissage automatique Python. 
NumPy permet des opérations efficaces sur les structures de données souvent utilisées en apprentissage automatique : **vecteurs**, **matrices** et **tenseurs ou flow des matrices**. 

## 1.1 Création d'un vecteur

In [134]:
import numpy as np  #importation du librarie numpy

vecteur_ligne = np.array([1, 2, 3])  #Creation du vecteur sous forme d'une ligne

vecteur_colonne = np.array([[1],[2], [3]]) #Creation du vecteur sous forme d'une ligne

In [135]:
vecteur_ligne     # Affichage du vecteur_ligne

array([1, 2, 3])

In [136]:
vecteur_colonne    #affichage du vecteur_colonne

array([[1],
       [2],
       [3]])

**Nota** : La structure de données principale de NumPy est le tableau multidimensionnel. Pour créer un vecteur, nous créons simplement un tableau unidimensionnel. Tout comme les vecteurs, ces tableaux peuvent être représentés horizontalement (c'est-à-dire des lignes) ou verticalement (c'est-à-dire des colonnes).

## 1.2 Création d'une matrice

In [137]:
matrice = np.array([[1, 2],
                    [4, 7], 
                    [13, 9]]) # Creatin de la matrice a 3 lignes et 2 colonnes avec numpy
matrice

array([[ 1,  2],
       [ 4,  7],
       [13,  9]])

Pour créer une matrice avec Numpy, nous pouvons utiliser un tableau bidimensionnel. Dans notre exercice précédent, la matrice contient trois lignes et deux colonnes.

Cependant, la structure des données matricielles n’est pas recommandée pour deux raisons. Premièrement, les tableaux constituent la structure de données standard de facto de NumPy. Deuxièmement, la grande majorité des opérations NumPy renvoient des tableaux, pas des objets matriciels.

## 1.3 Sélection des éléments d'une matrices

In [138]:
vecteur = np.array([1, 2, 3, 4, 5, 6])  # Creation du vecteur sous forme d'une ligne

matrice = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) # Creation d'une matrice de 3 lignes et 3 colonnes.

vecteur[2]  # Sélectionnez le troisième élément du vecteur

3

In [139]:
matrice[1,1]   # Sélectionnez la deuxième ligne, la deuxième colonne

5

**Nota** : Comme la plupart des éléments en Python, les tableaux NumPy sont indexés à zéro, ce qui signifie que l'index du premier élément est 0 et non 1. Avec cette mise en garde, NumPy propose une grande variété de méthodes pour sélectionner (c'est-à-dire indexer et découper) des éléments ou des groupes. d'éléments dans des tableaux :

In [140]:
# Sélectionner tous les éléments d'un vecteur
vecteur[:]

array([1, 2, 3, 4, 5, 6])

In [141]:
# Sélectionnez tout jusqu'au troisième élément inclus
vecteur[:3]

array([1, 2, 3])

In [142]:
# Sélectionnez tout après le troisième élément
vecteur[3:]

array([4, 5, 6])

In [143]:
# Sélectionnez le dernier élément
vecteur[-1]

6

In [144]:
# Sélectionnez les deux premières lignes et toutes les colonnes d'une matrice
matrice[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
# Sélectionnez toutes les lignes et la deuxième colonne
matrice[:,1:2]

array([[2],
       [5],
       [8]])

## 1.4 Décrire une matrice

In [146]:
matrice = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

matrice.shape # Afficher le nombre de lignes et de colonnes

(3, 4)

In [147]:
matrice.size  # Afficher le nombre d'éléments (lignes * colonnes)

12

In [148]:
matrice.ndim  # Afficher le nombre de dimensions

2

Cela peut sembler basique (et ça l’est) ; cependant, il sera toujours utile de vérifier la forme et la taille d'un réseau à la fois pour des calculs ultérieurs et simplement pour une vérification intestinale après une opération.

## 1.5 Application d'opérations aux éléments

In [149]:
matrice = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Créer une fonction qui ajoute 100 à quelque chose
ajoute_100 = lambda i: i + 100

# Créer une fonction vectorisée
vectorized_ajoute_100 = np.vectorize(ajoute_100)

# Appliquer la fonction à tous les éléments de la matrice
vectorized_ajoute_100(matrice)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

**Nota**: La classe vectorize de NumPy convertit une fonction en une fonction qui peut s'appliquer à tous les éléments d'un tableau ou d'une tranche d'un tableau. Il convient de noter que la vectorisation est essentiellement une boucle for sur les éléments et n'augmente pas les performances. De plus, les tableaux NumPy nous permettent d'effectuer des opérations entre tableaux même si leurs dimensions ne sont pas les mêmes (un processus appelé diffusion). Par exemple, nous pouvons créer une version beaucoup plus simple de notre solution en utilisant la diffusion :

In [150]:
# Ajoutez 100 à tous les éléments
matrice + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.6 Recherche des valeurs maximales et minimales

In [151]:
matrice = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Renvoie l'élément maximum
np.max(matrice)

9

In [152]:
# Renvoie l'élément minimum
np.min(matrice)

1

**Nota** : Nous souhaitons souvent connaître la valeur maximale et minimale d’un tableau ou d’un sous-ensemble d’un tableau. Cela peut être accompli avec les méthodes max et min. En utilisant le paramètre axis, nous pouvons également appliquer l'opération le long d'un certain axe :

In [153]:
# Trouver le maximum d'éléments dans chaque colonne
np.max(matrice, axis=0)

array([7, 8, 9])

In [154]:
# Trouver le minimum d'éléments dans chaque colonne
np.max(matrice, axis=1)

array([3, 6, 9])

## 1.7 Calcul de la moyenne, de la variance et de l'écart type

In [155]:
matrice = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Moyenne de retour
np.mean(matrice)

5.0

In [156]:
# Retourne la variance
np.var(matrice)

6.666666666666667

In [157]:
# Retourne la standard deviation (ecart type)
np.std(matrice)

2.581988897471611

Tout comme avec max et min, nous pouvons facilement obtenir des statistiques descriptives sur l'ensemble de la matrice ou effectuer des calculs le long d'un seul axe :

In [158]:
# Trouver la valeur moyenne dans chaque colonne
np.mean(matrice, axis=0)

array([4., 5., 6.])

## 1.8 Reshaping Arrays ou Remodelage des tableaux

In [159]:
matrice = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]]) #Creation d'une matrice de 4 lignes et 3 colonnes.

In [160]:
# Remodeler la matrice en matrice 2x6
matrice.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

reshape nous permet de restructurer un tableau afin que nous conservions les mêmes données mais qu'il soit organisé en un nombre différent de lignes et de colonnes. La seule exigence est que la forme de la matrice originale et de la nouvelle matrice contienne le même nombre d'éléments (c'est-à-dire la même taille). Nous pouvons voir la taille d'une matrice en utilisant size :

In [161]:
matrice.size

12

**Nota**: Un argument utile dans reshape est -1, ce qui signifie en fait « autant que nécessaire », donc reshape(-1, 1) signifie une ligne et autant de colonnes que nécessaire :

In [162]:
matrice.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

Enfin, si nous fournissons un entier, reshape renverra un tableau 1D de cette longueur :

In [163]:
matrice.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.9 Transposer un vecteur ou une matrice

In [164]:
matrice = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Transposer la matrice
matrice.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Nota**: La transposition est une opération courante en algèbre linéaire où les indices de colonne et de ligne de chaque élément sont permutés. Un point nuancé qui est généralement négligé en dehors d’une classe d’algèbre linéaire est que, techniquement, un vecteur ne peut pas être transposé car il s’agit simplement d’une collection de valeurs :

In [165]:
# Transposer le vecteur
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

Cependant, il est courant de parler de transposition d'un vecteur comme de la conversion d'un vecteur ligne en vecteur colonne (notez la deuxième paire de crochets) ou vice versa :

In [166]:
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.10 Aplatir une matrice

In [167]:
matrice = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Aplatir la matrice
matrice.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

flatten est une méthode simple pour transformer une matrice en un tableau unidimensionnel. Alternativement, nous pouvons utiliser reshape pour créer un vecteur ligne :

In [168]:
matrice.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 1.11 Trouver le rang d'une matrice

In [169]:
matrice = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Renvoyer le rang de la matrice
np.linalg.matrix_rank(matrice)

2

Le rang d'une matrice correspond aux dimensions de l'espace vectoriel couvert par ses colonnes ou ses lignes. Trouver le rang d'une matrice est facile dans NumPy grâce à Matrix_rank.

## 1.12 Calcul du déterminant

In [170]:
matrice = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Retourne le Déterminant de la matrice
np.linalg.det(matrice)

0.0

Il peut parfois être utile de calculer le déterminant d'une matrice. NumPy rend cela facile avec det.

## 1.13 Obtenir la diagonale d'une matrice

In [171]:
matrice = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Retourne les éléments diagonaux
matrice.diagonal()

array([1, 4, 9])

NumPy facilite l'obtention des éléments diagonaux d'une matrice avec la diagonale. Il est également possible d'obtenir une diagonale par rapport à la diagonale principale en utilisant le paramètre offset :

In [172]:
# Retourne la diagonale une au-dessus de la diagonale principale
matrice.diagonal(offset=1)

array([2, 6])

In [173]:
# Retourne la diagonale une au-dessous de la diagonale principale
matrice.diagonal(offset=-1)

array([2, 8])

## 1.14 Calcul de la trace d'une matrice

In [174]:
matrice = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Retourne la Trace d'une matrice
matrice.trace()

14

La trace d'une matrice est la somme des éléments diagonaux et est souvent utilisée sous le capot dans les méthodes d'apprentissage automatique. Étant donné un tableau multidimensionnel NumPy, nous pouvons calculer la trace à l'aide de trace. On peut aussi renvoyer la diagonale d'une matrice et calculer sa somme :

In [175]:
# Renvoie les éléments de diagonale et de somme
sum(matrice.diagonal())

14

## 1.15 Recherche de valeurs propres et de vecteurs propres

Les vecteurs propres sont largement utilisés dans les bibliothèques d'apprentissage automatique. Intuitivement, étant donné une transformation linéaire représentée par une matrice A, les vecteurs propres sont des vecteurs qui, lorsque cette transformation est appliquée, ne changent que d'échelle (et non de direction). Plus formellement:

                                                        Av = λv
                                                        
où A est une matrice carrée, λ contient les valeurs propres et v contient les vecteurs propres. Dans l'ensemble d'outils d'algèbre linéaire de NumPy, eig nous permet de calculer les valeurs propres et les vecteurs propres de n'importe quelle matrice carrée.

In [176]:
matrice = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]]) #Creation d'une matrice de 3 lignes et 3 colonnes.

# Calculer les valeurs propres et les vecteurs propres
eigenvalues, eigenvectors = np.linalg.eig(matrice)
#Affiche les valeurs propres
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [177]:
# Afficher les vecteurs propres
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 1.16 Calcul des produits scalaires

Le produit scalaire de deux vecteurs, a et b, est défini comme :


$$
{\sum_{i = 1}^{n} {a_i}{b_i}}
$$

où ai est le ième élément du vecteur a. Nous pouvons utiliser la classe dot de NumPy pour calculer le produit scalaire. Alternativement, dans Python 3.5+, nous pouvons utiliser le nouvel opérateur @ :

In [178]:
# Création de deux vecteurs
vecteur_a = np.array([1,2,3]) 
vecteur_b = np.array([4,5,6])
# Calculate dot product
np.dot(vecteur_a, vecteur_b)

32

In [179]:
# Calculate dot product
vecteur_a @ vecteur_b

32

## 1.17 Ajout et soustraction de matrices

In [180]:
#Creation d'une matrice de 3 lignes et 3 colonnes.
matrice_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

#Creation d'une matrice de 3 lignes et 3 colonnes.
matrice_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])
# L'addition de deux matrices
np.add(matrice_a, matrice_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [181]:
# Soustraction de deux matrices
np.subtract(matrice_a, matrice_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

Alternativement, nous pouvons simplement utiliser les opérateurs + et - :

In [182]:
# Addition de deux matrices
matrice_a + matrice_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.18 Multiplication de matrices

In [183]:
# Creation de la premiere matrice_a
matrice_a = np.array([[1, 1],
                     [1, 2]])
# Creation de la deuxieme matrice_b
matrice_b = np.array([[1, 3],
                     [1, 2]])
# Multiplication de deux matrices
np.dot(matrice_a, matrice_b)

array([[2, 5],
       [3, 7]])

Alternativement, dans Python 3.5+, nous pouvons utiliser l'opérateur @ :

In [184]:
# Multiplier deux matrices
matrice_a @ matrice_b

array([[2, 5],
       [3, 7]])

Si nous voulons effectuer une multiplication élément par élément, nous pouvons utiliser l'opérateur * :

In [185]:
# Multiplier deux matrices par éléments
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

## 1.19 Inverser une matrice

L’inverse d’une matrice carrée, A, est une deuxième matrice  $A^{-1}$ telle que $A.A^{-1}= I$ :

où I est la matrice identité. Dans NumPy, nous pouvons utiliser linalg.inv pour calculer A–1 s'il existe. Pour voir cela en action, nous pouvons multiplier une matrice par son inverse et le résultat est la matrice identité :

In [186]:
# Creation de la matrice
matrice = np.array([[1, 4],
                   [2, 5]])
# Calculer l'inverse de la matrice
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [187]:
# Matrice de multiplication et son inverse
matrice @ np.linalg.inv(matrice)

array([[1., 0.],
       [0., 1.]])

## 1.20 Génération de valeurs aléatoires

NumPy offre une grande variété de moyens pour générer des nombres aléatoires, bien plus que ce qui peut être abordé ici. Dans notre solution, nous avons généré des flottants:

In [188]:
# Set seed
np.random.seed(0)
# Générer trois flottants aléatoires entre 0,0 et 1,0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [189]:
# Générer trois entiers aléatoires entre 1 et 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

In [190]:
# Alternativement, nous pouvons générer des nombres en tirant d'une distribution :
# Génére trois nombres d'une distribution normale de moyenne 0,0
# et écart type de 1,0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [191]:
#Génére trois nombres à partir d'une distribution logistique avec une moyenne de 0,0 et une échelle de 1,0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [192]:
#Génére trois nombres supérieurs ou égaux à 1,0 et inférieurs à 2,0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])


                                        
                                                        Contacts
                                             - mbulayi.onesime@unikin.ac.cd
                                                   - mbonesime@gmai.com